name: delete-old-versions
on:
  workflow_dispatch:
    inputs:
      package_version_ids:
        required: false
        
      delete_only_pre_release_versions:
        required: false
        
      package_name:
        required: false
        
      package_type:
        required: false
        
      num_old_versions_to_delete:
        required: false
        
      min_versions_to_keep:
        required: false
        
      ignore_versions:
        required: false
        
      owner:
        required: false

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@s-anupam-rest-api
        with: 
            owner: ${{ inputs.owner }}
            package-name: ${{ inputs.package_name }}
            package-type: ${{ inputs.package_type }}
            delete-only-pre-release-versions: ${{ inputs.delete_only_pre_release_versions }}
            num-old-versions-to-delete: ${{ inputs.num_old_versions_to_delete }}
            min-versions-to-keep: ${{ inputs.min_versions_to_keep }}
            ignore-versions: ${{ inputs.ignore_versions }}
            package-version-ids: ${{ inputs.package_version_ids }}
