name: delete-old-versions
on:
  workflow_dispatch:
  push:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@280935cb1a537672d6f6bb39922ce37ffff40705
        with: 
            owner: s-anupam
            repo: 'npm-test-pkg'
            package-name: 'npm-test-pkg'
            min-versions-to-keep: 1
            package-type: 'npm'
            
