name: delete-old-versions-wd
on:
  workflow_dispatch:

jobs:
  delete-old-versions-wd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@s-anupam-testing
        with: 
            package-name: 'alpine'
            package-type: 'container'
            min-versions-to-keep: 3
            delete-only-untagged-versions: true
