name: delete-old-versions-push
on:
  push:

jobs:
  delete-old-packages-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@s-anupam-rest-api
        with: 
            package-name: 'npm-test-pkg'
            package-type: 'npm'
            package-version-ids: 61654272,61654265,61654261,61654256,61654252
            min-versions-to-keep: 300
