name: delete-old-versions
on:
  workflow_dispatch:
  push:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@s-anupam-rest-api
        with: 
            owner: 's-anupam'
            repo: 'npm-test-pkg'
            package-name: 'npm-test-pkg'
            package-type: 'npm'
            delete-only-pre-release-versions: true
