name: delete-old-versions-push
on:
  push:

jobs:
  delete-old-packages-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@s-anupam-rest-api
        with: 
            package-name: 'npm-test-pkg'
            package-type: 'npm'
            ignore-versions: '^(0|[1-9]\d*)\.0\.0$'
            num-old-versions-to-delete: 90
