name: delete-old-versions
on:
  workflow_dispatch:
  push:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@e521d9e753ae867c150eee3a19710fe8e3f0f333
        with: 
            owner: 's-anupam'
            repo: 'npm-test-pkg'
            package-name: 'npm-test-pkg'
            min-versions-to-keep: 5
            package-type: 'npm'
