name: delete-old-versions-push
on:
  push:

jobs:
  delete-old-packages-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@s-anupam-rest-api
        with: 
            package-name: 'ubuntu'
            package-type: 'container'
            min-versions-to-keep: 2
