name: delete-old-versions
on:
  workflow_dispatch:
    inputs:
      delete_only_pre_release_versions:
        required: false
  push:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@ng-fix-deletion
        with: 
            owner: 's-anupam'
            repo: 'npm-test-pkg'
            package-name: 'npm-test-pkg'
            package-type: 'npm'
            delete-only-pre-release-versions: ${{ inputs.delete_only_pre_release_versions }}
