name: delete-old-versions-wd
on:
  workflow_dispatch:

jobs:
  delete-old-versions-wd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@s-anupam-untagged-flag
        with: 
            package-name: 'npm-test-pkg'
            package-type: 'npm'
            min-versions-to-keep: 5
            delete-only-untagged-versions: false
